services:
  olivos:
    image: ghcr.io/cary17/olivos:latest
    image: cary17/olivos:latest
    container_name: olivos
    restart: always
    volumes:
      - ./conf:/app/OlivOS/conf
      - ./plugin:/app/OlivOS/plugin
    environment:
      TZ: Asia/Shanghai
      # 添加额外 pip 依赖，多个用空格分隔
      #EXTRA_PACKAGES: "psutil==5.9.0 lxml>=4.9"
      pass:
